# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aomman <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/15 18:59:19 by aomman            #+#    #+#              #
#    Updated: 2022/11/15 18:59:20 by aomman           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = megaphone

all:${NAME}

${NAME}:
	c++ -Wall -Werror -Wextra megaphone.cpp -o megaphone
clean:
	rm -f ${NAME}
fclean : clean

re : fclean all
