# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aomman <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/03 13:05:46 by aomman            #+#    #+#              #
#    Updated: 2023/01/04 18:59:24 by aomman           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = temp

all : ${NAME}

${NAME} : 
	c++ -Wall -Wextra -Werror -std=c++98 main.cpp -o ${NAME}

clean : 
	rm -f ${NAME}

fclean : clean

re : fclean all

