# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aomman <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/01/04 21:14:53 by aomman            #+#    #+#              #
#    Updated: 2023/01/04 21:16:21 by aomman           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = iter

all : ${NAME}

${NAME} : 
	c++ -Wall -Wextra -Werror -std=c++98 main.cpp iter.cpp -o ${NAME}

clean :	
	rm -f ${NAME}

fclean : clean

re : fclean all
